// <auto-generated />
namespace LibraryMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modified_Phone_Mem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modified_Phone_Mem));
        
        string IMigrationMetadata.Id
        {
            get { return "202406051402241_Modified_Phone_Mem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
